/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PickupRequest {
  'id' : bigint,
  'status' : RequestStatus,
  'destination' : string,
  'farmerId' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'preferredDate' : string,
  'notes' : string,
  'quantity' : string,
  'cropType' : string,
  'transporterId' : [] | [Principal],
  'transporterName' : [] | [string],
  'farmerName' : string,
  'pickupLocation' : string,
}
export type RequestStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface UserProfile {
  'userRole' : UserRole,
  'name' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelRequest' : ActorMethod<[bigint], undefined>,
  'completeDelivery' : ActorMethod<[bigint], undefined>,
  'createRequest' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'getAllRequests' : ActorMethod<[], Array<PickupRequest>>,
  'getAvailableRequests' : ActorMethod<[], Array<PickupRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRequests' : ActorMethod<[], Array<PickupRequest>>,
  'getMyTrips' : ActorMethod<[], Array<PickupRequest>>,
  'getRequestById' : ActorMethod<[bigint], [] | [PickupRequest]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'register' : ActorMethod<[string, string, UserRole], UserProfile>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startDelivery' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];