/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const PickupRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : RequestStatus,
  'destination' : IDL.Text,
  'farmerId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'preferredDate' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Text,
  'cropType' : IDL.Text,
  'transporterId' : IDL.Opt(IDL.Principal),
  'transporterName' : IDL.Opt(IDL.Text),
  'farmerName' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'userRole' : UserRole,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const VehicleInfo = IDL.Record({
  'vehicleType' : IDL.Text,
  'vehicleCapacity' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'requestId' : IDL.Nat,
  'text' : IDL.Text,
  'fromPrincipal' : IDL.Principal,
  'timestamp' : IDL.Int,
  'fromName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelRequest' : IDL.Func([IDL.Nat], [], []),
  'completeDelivery' : IDL.Func([IDL.Nat], [], []),
  'createRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'getAvailableRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerVehicleInfo' : IDL.Func([], [IDL.Opt(VehicleInfo)], ['query']),
  'getMessagesByRequest' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'getMyTrips' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
  'getRequestById' : IDL.Func([IDL.Nat], [IDL.Opt(PickupRequest)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [UserProfile], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveVehicleInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'startDelivery' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const PickupRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : RequestStatus,
    'destination' : IDL.Text,
    'farmerId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'preferredDate' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Text,
    'cropType' : IDL.Text,
    'transporterId' : IDL.Opt(IDL.Principal),
    'transporterName' : IDL.Opt(IDL.Text),
    'farmerName' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'userRole' : UserRole,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const VehicleInfo = IDL.Record({
    'vehicleType' : IDL.Text,
    'vehicleCapacity' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'requestId' : IDL.Nat,
    'text' : IDL.Text,
    'fromPrincipal' : IDL.Principal,
    'timestamp' : IDL.Int,
    'fromName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelRequest' : IDL.Func([IDL.Nat], [], []),
    'completeDelivery' : IDL.Func([IDL.Nat], [], []),
    'createRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'getAvailableRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerVehicleInfo' : IDL.Func([], [IDL.Opt(VehicleInfo)], ['query']),
    'getMessagesByRequest' : IDL.Func([IDL.Nat], [IDL.Vec(Message)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'getMyTrips' : IDL.Func([], [IDL.Vec(PickupRequest)], ['query']),
    'getRequestById' : IDL.Func([IDL.Nat], [IDL.Opt(PickupRequest)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([IDL.Text, IDL.Text, UserRole], [UserProfile], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveVehicleInfo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'sendMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'startDelivery' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
